name: lokiplay-nakama
logger:
  level: INFO
  format: json
session:
  token_expiry_sec: 3600
socket:
  max_message_size_bytes: 4096
  max_request_size_bytes: 8192
  ping_period_ms: 5000
  pong_timeout_ms: 10000
runtime:
  js_entrypoint: loki.js
  path: /nakama/data/modules
